# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'iosApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_modular_headers!
  pod "FirebaseCore"
  pod "FirebaseAuth"
  pod "FirebaseAnalytics"
  pod "GoogleSignIn"
  pod "GoogleSignInSwift"

  # Pods for iosApp

end
